language:
  python

python:
  - 3.6

before_install:
  - locale-gen en_US fa_IR
  - locale -a
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
  - pip install --upgrade pytest

install:
  pip install -e .

script:
  py.test -vv --cov-report term-missing:skip-covered --cov=restiro

after_success:
  coveralls
